version: '2'
services:
  lb:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
      - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  dns:
    image: steamcache/steamcache-dns:latest
    ports:
      - 53:53/udp
    environment:
      USE_GENERIC_CACHE: true
      LANCACHE_IP: ${LANCACHE_IP}
      UPSTREAM_DNS: ${UPSTREAM_DNS}
  sniproxy:
    image: steamcache/sniproxy:latest
    ports:
        - 443:443/tcp
  apple:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/apple/cache:/data/cache
      - ${CACHE_ROOT}/apple/logs:/data/logs
  arenanet:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/arenanet/cache:/data/cache
      - ${CACHE_ROOT}/arenanet/logs:/data/logs
  blizzard:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/blizzard/cache:/data/cache
      - ${CACHE_ROOT}/blizzard/logs:/data/logs
  daybreak:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/daybreak/cache:/data/cache
      - ${CACHE_ROOT}/daybreak/logs:/data/logs
  frontier:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/frontier/cache:/data/cache
      - ${CACHE_ROOT}/frontier/logs:/data/logs
  gog:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/gog/cache:/data/cache
      - ${CACHE_ROOT}/gog/logs:/data/logs
  hirez:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/hirez/cache:/data/cache
      - ${CACHE_ROOT}/hirez/logs:/data/logs
  minecraft:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/minecraft/cache:/data/cache
      - ${CACHE_ROOT}/minecraft/logs:/data/logs
  nexusmods:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/nexusmods/cache:/data/cache
      - ${CACHE_ROOT}/nexusmods/logs:/data/logs
  nintendo:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/nintendo/cache:/data/cache
      - ${CACHE_ROOT}/nintendo/logs:/data/logs
  origin:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/origin/cache:/data/cache
      - ${CACHE_ROOT}/origin/logs:/data/logs
  riot:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/riot/cache:/data/cache
      - ${CACHE_ROOT}/riot/logs:/data/logs
  rockstar:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/rockstar/cache:/data/cache
      - ${CACHE_ROOT}/rockstar/logs:/data/logs
  sony:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/sony/cache:/data/cache
      - ${CACHE_ROOT}/sony/logs:/data/logs
  steam:
    image: steamcache/${STEAMCACHE_CONTAINER}:latest
    volumes:
      - ${CACHE_ROOT}/steam/cache:/data/cache
      - ${CACHE_ROOT}/steam/logs:/data/logs
  uplay:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/uplay/cache:/data/cache
      - ${CACHE_ROOT}/uplay/logs:/data/logs
  twitch:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/twitch/cache:/data/cache
      - ${CACHE_ROOT}/twitch/logs:/data/logs
  wargaming:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/wargaming/cache:/data/cache
      - ${CACHE_ROOT}/wargaming/logs:/data/logs
  wsus:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/wsus/cache:/data/cache
      - ${CACHE_ROOT}/wsus/logs:/data/logs
  xboxlive:
    image: steamcache/generic:latest
    volumes:
      - ${CACHE_ROOT}/xboxlive/cache:/data/cache
      - ${CACHE_ROOT}/xboxlive/logs:/data/logs
