name: lancache-generic
description: |
      This docker container provides a caching proxy server for game download content. For any network with more than one PC gamer in connected this will drastically reduce internet bandwidth consumption.
version: v1.0.0
category: Caching
maintainer: Jessica Smith, Robin Lewis, Brian Wojtczak, Jason Rivers
license: MIT License
projectURL: "https://steamcache.net"

